{% set version = "3.0.8" %}

package:
  name: swig
  version: {{ version }}

source:
  fn: swig-{{ version }}.tar.gz                                             # [not win]
  url: http://prdownloads.sourceforge.net/swig/swig-{{ version }}.tar.gz    # [not win]
  sha256: 58a475dbbd4a4d7075e5fe86d4e54c9edde39847cdb96a3053d87cb64a23a453  # [not win]
  fn: swigwin-{{ version }}.zip                                             # [win]
  url: http://prdownloads.sourceforge.net/swig/swigwin-{{ version }}.zip    # [win]
  sha256: e5fe65ae9b145ea3c00172abdb527f2d3458e8cc928e25db984b2da1b00a2a04  # [win]

build:
  number: 1
  detect_binary_files_with_prefix: True  # [not win]

requirements:
  build:
    - toolchain
    - pcre  # [not win]
    - python  # [not win]
    - boost  # [not win]
  run:
    - pcre  # [not win]
    - boost  # [not win]

test:
  commands:
    - swig -help

about:
  home: http://www.swig.org/
  license: GPL-3.0
  summary: 'C/C++ parser code generator.'

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
