{% set version = "4.0.0" %}

package:
  name: swig
  version: {{ version }}

source:
  fn: swig-{{ version }}.tar.gz  # [unix]
  url: http://prdownloads.sourceforge.net/swig/swig-{{ version }}.tar.gz  # [unix]
  sha256: e8a39cd6437e342cdcbd5af27a9bf11b62dc9efec9248065debcb8276fcbb925  # [unix]
  fn: swigwin-{{ version }}.zip  # [win]
  url: http://prdownloads.sourceforge.net/swig/swigwin-{{ version }}.zip  # [win]
  sha256: 1391aecad92e365b960eb1a1db3866ca1beee61b3395c182298edbf323d1695a  # [win]

build:
  number: 0
  skip: true  # [not py27 and not win]
  detect_binary_files_with_prefix: true  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pcre  # [unix]
    - python  # [unix]
  run:
    - pcre  # [unix]

test:
  commands:
    - swig  -help

about:
  home: http://www.swig.org/
  license: GPL 3
  summary: C/C++ parser code generator

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
