{% set version = "4.2.0" %}

package:
  name: swig
  version: {{ version }}

source:
  fn: swig-{{ version }}.tar.gz
  url: http://prdownloads.sourceforge.net/swig/swig-{{ version }}.tar.gz
  sha256: 261ca2d7589e260762817b912c075831572b72ff2717942f75b3e51244829c97

build:
  number: 1

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]
    - cmake  # [win]
    - winflexbison  # [win]
  host:
    - pcre2

test:
  commands:
    - swig -help
    - swig -swiglib

about:
  home: http://www.swig.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: C/C++ parser code generator
  description: |
    SWIG is an interface compiler that connects programs written in C and C++
    with scripting languages such as Perl, Python, Ruby, and Tcl. It works by
    taking the declarations found in C/C++ header files and using them to
    generate the wrapper code that scripting languages need to access the
    underlying C/C++ code. In addition, SWIG provides a variety of
    customization features that let you tailor the wrapping process to suit
    your application.
  dev_url: https://github.com/swig/swig
  doc_url: https://www.swig.org/doc.html

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - msarahan
    - ocefpaf
