travis:
  secure:
    BINSTAR_TOKEN: DGKqbXqQcDJ4FiENqWBEXUmmuvDqBqYpBk6xtwPlSkYN5A3wT6jPUvh4HMvCiaFiLdK2lxxeujl1unY6OHqMjGHfWCCan8VWkoRAb0Qys93rO2iLp8UtuEaploCGx7vpon07rS9VnvGLraN4TBAyESvWOTE64c2Sr5lIVqO3jWnZXcO4ThTeGSbpNIVGDdu0wi7VHy6XqdDACNGxVJ1oLeUKJfxp5NqNfAk6MgiGjPE2J1OJ5iMXy1GRlhfTJqXV5daPjeQNBv7muSq6dNw4TpEJRy+QvCHRVSpI3CioYsDCx4fS0h2ZoZnd5AkgGAiAe0RkNAetxiSzSndIeWieyGpMteYH4z9Bx/NmVU4udP+jwjNnjTINon6ZJtrCv6YRjpyre3kcsW3O5UxNOsomtGr70j0mxI4BbiRjlSzxMm1Uxa/YdguQXzuKSBKeg8c0QLKxdV/w1GfXU8GQCn6Ec/Y70XbOYXQjT9hAVkE9Bh2QI1WdtBsPPh6Q0rrRll7dONAoyOmYhM498+H7cRQrOOqrVmRe8Vv6nekhcFb4veNTfAAZBu42hcSPt6GpLduDrvReYrvf9sEW8JN5XuGNVd+emwlbeJ8mIgivinDTdkrX6Z4M+3nqoRYMBl6wj7sLKl6SPlBVWqwjUbquVTJ2fLVMXRq3zpfcfTZiB8ldkzE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
